### ISSUE TITLE
Render the Story Maps URL

### ISSUE THREAD

**Issue by cderose** [YaleDHLab/nhba#291]
In the edit screen for the building record, there's a place for a 'Story Map Url'. Could that URL (when provided) appear on the public-facing building page at the top with the other record information? 
![screen shot 2018-01-22 at 3 15 35 pm](https://user-images.githubusercontent.com/15657357/35242295-2643d5c8-ff87-11e7-9360-3556cc4153c5.png)

**Comment by pleonard212** [comment]
No styling required here (Beyond the basic sans-serif font) until we have time to do a design update.
