### ISSUE TITLE
Re-skin of building info heirarchy

### ISSUE THREAD

**Issue by pleonard212** [YaleDHLab/nhba#294]
So this does not change data structures, but instead "promotes" the current H3 elements:

- Physical Description
- Urban Setting
- Social History
- Site History

 ... to have H2 styling instead.

In addition, it eliminates the "Building History" as the governing unit.  

Instead, each of the four bullet points above will appear -- if they contain any text.  

We can re-use the "Building History" icon (The 2 skyscrapers) for each of these four sections the left-hand nav until we have a chance to do a design review.

**Comment by duhaime** [comment]
@pleonard212 @cderose These changes are all now live  -- if you take a look and want me to follow up on any of the issues, I'm happy to do so!

**Comment by cderose** [comment]
@duhaime it all works beautifully, thank you!

**Comment by pleonard212** [comment]
@duhaime Fantastic!

**Comment by duhaime** [comment]
:raised_hands: Woohoo :raised_hands:
