### ISSUE TITLE
Allow Non-Admin Users to Create and Edit Buildings

### ISSUE THREAD

**Issue by spaceraccoon** [YaleDHLab/nhba#311]
Non-admin users should be able to create buildings and edit the buildings they've created.
- At the moment the database does not support it; the `building` model should include a `creator` property and the `user` model should include a `buildings` property. This requires a DB migration.
- Permissions at the `/buildings/update` route need to be modified
- Front-end changes to allow adding buildings

**Comment by spaceraccoon** [comment]
@duhaime As far as I can tell there is no one-to-many relationship expressed in the current `user` and `building` models. Does this look right?

**Comment by duhaime** [comment]
@spaceraccoon I'm not quite sure what you mean. The initial app requirements had a simple user model--only admins could create/edit buildings, and only superadmins could appoint admins. There was no notion of a user-building relationship beyond the simple rights model described above. Does this answer your question?

**Comment by spaceraccoon** [comment]
Yep that answers my question, thanks. I might have to run a database migration in this case as they want for non-admins to be able the create buildings and edit the buildings they have created, requiring some sort of relationship.

**Comment by spaceraccoon** [comment]
DB models and backend support updated in #313

**Comment by duhaime** [comment]
@spaceraccoon Sounds good!
