### ISSUE TITLE
Users are not being created with a userId

### ISSUE THREAD

**Issue by spaceraccoon** [YaleDHLab/nhba#314]
When users are created, no `userId` attribute is being set. This is also not present in the current `user` model. This causes duplicate errors. Note that `userId` is different from the `_id` attribute, which is automatically generated by mongo. Mongo patterns generally suggest relying on `_id`.

As far as I can tell `userId` is currently only being used for ease of granting `superadmin` status via `db.users.update({'userId': 6}, {$set: {'superadmin': true}})`. However, this might cause confusion with `_id`. 

Either we have to set up an autoincrementing `userId` attribute and set it with user creation or remove `userId` altogether.

On the live instance, it appears that `userId` is only set for the first 16 users, which is likely because of this issue.

**Comment by duhaime** [comment]
@spaceraccoon This was caused by a legacy mongo autoincrement package, recently dropped as a dependency. This problem should be resolved on ec2, as I dropped the index on userId (and dropped all other indexes created by this package). To resolve this on your local machine, you should run in the mongo shell:

```
use nhba
show tables
db.TABLENAME.getIndexes()
```

Given an index with tablenameId, you should drop that index (e.g.):

```
> db.users.getIndexes()
[
	{
		"v" : 2,
		"key" : {
			"_id" : 1
		},
		"name" : "_id_",
		"ns" : "nhba.users"
	},
	{
		"v" : 2,
		"unique" : true,
		"key" : {
			"userId" : 1
		},
		"name" : "userId_1",
		"background" : true,
		"ns" : "nhba.users"
	}
]
> db.users.dropIndex('userId_1')
{ "nIndexesWas" : 2, "ok" : 1 }
>
```

Does this resolve your problem?

**Comment by duhaime** [comment]
P.S. The userId attribute is completely unused -- the presence of that attribute on early user records is benign but feel free to remove...

**Comment by spaceraccoon** [comment]
Thank you! Yes, I actually used those same commands in a migration file. I
wanted to check with you in case it was necessary for something else.
