### ISSUE TITLE
Minimal present attributes for building display

### ISSUE THREAD

**Issue by duhaime** [YaleDHLab/nhba#320]
@spaceraccoon Hey Eugene! It's great you've landed so many PR's on this app--thanks for that! It might be worth revisiting #317 though, as dropping that requirement leads to strange display properties:

![screen shot 2018-02-05 at 10 00 28 am](https://user-images.githubusercontent.com/4801116/35811122-ad6ebb56-0a5b-11e8-9284-700215bef603.png)

![screen shot 2018-02-05 at 10 00 36 am](https://user-images.githubusercontent.com/4801116/35811131-b140ac62-0a5b-11e8-8648-f1896ae1905d.png)

Are you talking with Elihu about requirements? If so and he's comfortable with the displays above, this can be closed, else maybe we should ping him to ask if he has minimal building features that should be present to facilitate display?

**Comment by spaceraccoon** [comment]
Makes sense! We didn't have form validation before but I'll check with Elihu about the requirements.

**Comment by duhaime** [comment]
Excellent, thank you

**Comment by duhaime** [comment]
Just a quick note to say there appear to be dozens of empty building stubs expressed in the client  (if one scrolls down a bit):

![screen shot 2018-02-09 at 1 47 30 pm](https://user-images.githubusercontent.com/4801116/36044324-41a721e0-0da0-11e8-8e68-dc428f279670.png)

**Comment by spaceraccoon** [comment]
Thanks for the heads up - I checked in with Them yesterday and they want some significant changes to the building entry form again (which will again require a model change/migration) but there are three required fields. I’ll work on it over this weekend and reject any building stubs that do not include those three fields.

**Comment by duhaime** [comment]
That sounds good @spaceraccoon!

**Comment by spaceraccoon** [comment]
To be fixed in #335 - googledoc specifying form/model changes are in there as well.

**Comment by spaceraccoon** [comment]
Resolved with #336
