### ISSUE TITLE
Modify Building Model and Entry Form

### ISSUE THREAD

**Issue by spaceraccoon** [YaleDHLab/nhba#335]
As per https://docs.google.com/document/d/1byMfHJRjI6aoPURj11c7w0ZLmejOyYcM_xFpHdskG0k/edit?ts=5a7c9d6d

**Comment by spaceraccoon** [comment]
Note: After discussion with Elihu, no model changes will be made. This will need to be seriously taken up by a future developer and migrated properly.

**Comment by spaceraccoon** [comment]
Hi @duhaime , how are all new select options being stored? Elihu wants the admin to be able to create new select options for multiselect fields via the form, but it doesn't appear to persist beyond state. I noticed that a previous version of the db does have a selects table.

**Comment by duhaime** [comment]
@spaceraccoon The selects table is created when one runs the install instructions in the README. Saved multiselect values appear to persist in that table (see Current Use) -- do they not on your machines?

![screen shot 2018-02-19 at 10 32 31 am](https://user-images.githubusercontent.com/4801116/36385345-5195152c-1560-11e8-8af1-5c474e1b2718.png)
